import { useEffect, useMemo, useState } from 'react';
import { Link, router } from 'expo-router';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { requireSupabase } from '../lib/supabase';

type Provider = { id:string; name:string; city:string; role:string; bio:string|null; hourly_rate:number; languages:string[]|null; verified:boolean; rating?:number };
const roles=['All','Friend','Conversation','Gaming','Activity','Event','Travel','GF/BF role-play'];

export default function Home(){
 const [providers,setProviders]=useState<Provider[]>([]),[role,setRole]=useState('All'),[city,setCity]=useState(''),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{load()},[]);
 async function load(){try{const s=requireSupabase();const {data,error}=await s.from('shokon_providers').select('id,name,city,role,bio,hourly_rate,languages,verified').eq('active',true).order('created_at',{ascending:false});if(error)throw error;setProviders(data||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 const filtered=useMemo(()=>providers.filter(p=>(role==='All'||p.role===role)&&(!city.trim()||p.city.toLowerCase().includes(city.toLowerCase()))&&(`${p.name} ${p.city} ${p.role} ${p.bio||''}`.toLowerCase().includes(q.toLowerCase()))),[providers,role,city,q]);
 return <View style={s.screen}><View style={s.header}><View><Text style={s.logo}>SHOKON.</Text><Text style={s.tag}>Find someone to spend time with.</Text></View><Link href="/auth" asChild><Pressable style={s.outline}><Text>Sign in</Text></Pressable></Link></View><TextInput style={s.input} placeholder="Search people or roles" value={q} onChangeText={setQ}/><TextInput style={s.input} placeholder="City (e.g. Pristina)" value={city} onChangeText={setCity}/><FlatList horizontal data={roles} showsHorizontalScrollIndicator={false} keyExtractor={x=>x} contentContainerStyle={{gap:8,paddingVertical:4}} renderItem={({item})=><Pressable onPress={()=>setRole(item)} style={[s.chip,role===item&&s.chipActive]}><Text style={role===item?s.chipTextActive:undefined}>{item}</Text></Pressable>}/>{loading?<ActivityIndicator style={{marginTop:30}}/>:error?<Text style={s.error}>{error}</Text>:<FlatList data={filtered} keyExtractor={x=>x.id} contentContainerStyle={{paddingBottom:110}} ListEmptyComponent={<Text style={s.empty}>No active providers yet.</Text>} renderItem={({item})=><Pressable style={s.card} onPress={()=>router.push({pathname:'/provider/[id]',params:{id:item.id}})}><View style={s.avatar}><Text style={{fontSize:28}}>{item.role==='Gaming'?'🎮':item.role==='Travel'?'✈️':'😊'}</Text></View><View style={{flex:1}}><View style={s.row}><Text style={s.name}>{item.name}{item.verified?' ✓':''}</Text><Text style={s.price}>€{Number(item.hourly_rate).toFixed(0)}/h</Text></View><Text style={s.muted}>{item.role} · {item.city}</Text><Text style={s.bio} numberOfLines={2}>{item.bio||'Friendly companionship and good company.'}</Text><Text style={s.muted}>{item.languages?.join(' · ')||'Albanian · English'}</Text></View></Pressable>)} /><View style={s.bottom}><Link href="/bookings" asChild><Pressable><Text>Bookings</Text></Pressable></Link><Link href="/messages" asChild><Pressable><Text>Messages</Text></Pressable></Link><Link href="/provider" asChild><Pressable><Text>Become a Shokon</Text></Pressable></Link></View></View>
}
const s=StyleSheet.create({screen:{flex:1,padding:18,backgroundColor:'#f7f7f5'},header:{paddingTop:35,paddingBottom:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},logo:{fontSize:24,fontWeight:'900'},tag:{fontSize:16,marginTop:3,color:'#555'},outline:{borderWidth:1,borderColor:'#222',borderRadius:12,paddingHorizontal:14,paddingVertical:10},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd',borderRadius:12,padding:13,marginVertical:5,fontSize:15},chip:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd',borderRadius:20,paddingHorizontal:13,paddingVertical:9},chipActive:{backgroundColor:'#111',borderColor:'#111'},chipTextActive:{color:'#fff'},card:{backgroundColor:'#fff',borderRadius:18,padding:15,marginTop:12,flexDirection:'row',gap:13,borderWidth:1,borderColor:'#e5e5e5'},avatar:{width:62,height:62,borderRadius:16,backgroundColor:'#eee',alignItems:'center',justifyContent:'center'},row:{flexDirection:'row',justifyContent:'space-between',gap:8},name:{fontSize:18,fontWeight:'800'},price:{fontWeight:'800'},muted:{color:'#666',marginTop:3},bio:{marginVertical:8,lineHeight:20},error:{color:'#b00020',marginTop:20},empty:{textAlign:'center',marginTop:40,color:'#666'},bottom:{position:'absolute',bottom:12,left:18,right:18,backgroundColor:'#fff',borderRadius:16,padding:14,flexDirection:'row',justifyContent:'space-around',borderWidth:1,borderColor:'#ddd'}});
