'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const sb=()=>{const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return u&&k?createClient(u,k):null};
type Booking={id:string;customer_id:string;starts_at:string;ends_at:string;hours:number;hourly_rate:number;total_amount:number;status:string;payment_status?:string;notes:string|null;created_at:string;shokon_profiles?:{display_name:string|null;city:string|null}|null};
export default function Provider(){
 const [user,setUser]=useState<any>(null),[provider,setProvider]=useState<any>(null),[bookings,setBookings]=useState<Booking[]>([]),[name,setName]=useState(''),[city,setCity]=useState('Pristina'),[role,setRole]=useState('Friend'),[bio,setBio]=useState(''),[rate,setRate]=useState('10'),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{load()},[]);
 async function load(){const s=sb();if(!s){setMsg('Configure Supabase variables first.');setLoading(false);return}const {data:{user}}=await s.auth.getUser();if(!user){setMsg('Sign in first.');setLoading(false);return}setUser(user);const {data:p,error}=await s.from('shokon_providers').select('*').eq('user_id',user.id).maybeSingle();if(error){setMsg(error.message);setLoading(false);return}if(p){setProvider(p);setName(p.name||'');setCity(p.city||'Pristina');setRole(p.role||'Friend');setBio(p.bio||'');setRate(String(p.hourly_rate??10));await loadBookings(s,p.id)}setLoading(false)}
 async function loadBookings(s:any,pid:string){const {data,error}=await s.from('shokon_bookings').select('id,customer_id,starts_at,ends_at,hours,hourly_rate,total_amount,status,notes,created_at').eq('provider_id',pid).order('starts_at',{ascending:true});if(error){setMsg(error.message);return}const ids=(data||[]).map((b:any)=>b.customer_id).filter(Boolean);let profiles:any[]=[];if(ids.length){const r=await s.from('shokon_profiles').select('id,display_name,city').in('id',ids);profiles=r.data||[]}setBookings((data||[]).map((b:any)=>({...b,shokon_profiles:profiles.find((p:any)=>p.id===b.customer_id)||null})));}
 async function save(){const s=sb();if(!s||!user)return;if(!name.trim()||!bio.trim())return setMsg('Add your name and a short bio.');const {data,error}=await s.from('shokon_providers').upsert({user_id:user.id,name:name.trim(),city,role,bio:bio.trim(),hourly_rate:Number(rate),languages:['Albanian','English'],active:true,verified:provider?.verified??false},{onConflict:'user_id'}).select().single();if(error){setMsg(error.message);return}setProvider(data);setMsg('Profile saved.');await loadBookings(s,data.id)}
 async function updateBooking(id:string,patch:any){const s=sb();if(!s||!provider)return;const {error}=await s.from('shokon_bookings').update(patch).eq('id',id).eq('provider_id',provider.id);if(error)setMsg(error.message);else{setMsg('Booking updated.');await loadBookings(s,provider.id)}}
 if(loading)return <main style={{maxWidth:1000,margin:'50px auto',padding:24}}><p>Loading…</p></main>;
 return <main style={{maxWidth:1000,margin:'40px auto',padding:24}}><a href="/">← SHOKON</a><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginTop:18}}><div><h1>Provider dashboard</h1><p className="muted">Manage your profile, incoming bookings and cash payments.</p></div><a className="navbtn" href="/messages">Messages</a></div>{msg&&<p className="muted">{msg}</p>}
 {!user?null:<><section className="card" style={{padding:20,margin:'18px 0'}}><h2>{provider?'Your profile':'Become a Shokon'}</h2><div style={{display:'grid',gap:10}}><input className="authinput" placeholder="Display name" value={name} onChange={e=>setName(e.target.value)}/><input className="authinput" placeholder="City" value={city} onChange={e=>setCity(e.target.value)}/><select className="authinput" value={role} onChange={e=>setRole(e.target.value)}>{['Friend','Conversation','Gaming','Activity','Event','Travel','GF/BF role-play'].map(x=><option key={x}>{x}</option>)}</select><textarea className="authinput" rows={4} placeholder="Tell people about yourself" value={bio} onChange={e=>setBio(e.target.value)}/><input className="authinput" type="number" min="1" step="1" value={rate} onChange={e=>setRate(e.target.value)}/><button className="book" onClick={save}>{provider?'Save profile':'Publish profile'}</button></div></section>
 {provider&&<><h2>Incoming bookings</h2>{bookings.length===0&&<p className="muted">No bookings yet.</p>}{bookings.map(b=><BookingCard key={b.id} b={b} actions={b.status==='pending'?<><button className="book" onClick={()=>updateBooking(b.id,{status:'accepted'})}>Accept</button><button className="navbtn" onClick={()=>updateBooking(b.id,{status:'declined'})}>Decline</button></>:b.status==='accepted'?<><button className="book" onClick={()=>updateBooking(b.id,{status:'completed'})}>Mark completed</button>{b.payment_status!=='paid'&&<button className="navbtn" onClick={()=>updateBooking(b.id,{payment_status:'paid'})}>Cash received</button>}</>:b.status==='completed'&&b.payment_status!=='paid'?<button className="book" onClick={()=>updateBooking(b.id,{payment_status:'paid'})}>Cash received</button>:null}/>)}</>}
 </>}</main>}
function BookingCard({b,actions}:{b:Booking;actions:any}){return <article className="card" style={{padding:20,margin:'12px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h3 style={{margin:'0 0 6px'}}>{b.shokon_profiles?.display_name||'Customer'}</h3><div className="muted">{b.shokon_profiles?.city||'Location not set'} · {new Date(b.starts_at).toLocaleString()}</div></div><strong>€{Number(b.total_amount).toFixed(2)}</strong></div><p>Duration: {b.hours} hour · Status: <b>{b.status}</b> · Cash: <b>{b.payment_status||'unpaid'}</b></p>{b.notes&&<p className="muted">{b.notes}</p>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{actions}</div></article>}
